### ISSUE TITLE
Discussion of normalization independent of code

### ISSUE THREAD

**Issue by eepLearning** [IdanAchituve/pFedGP#2]
Dear author

In addition, there is a discussion that I am curious about your opinion.

In most cases, normalization is applied to datasets such as Cifar10 and Cifar100 in PFL.
 In fact, I wonder if this normalization is justifiable in terms of not knowing the distribution of the entire dataset from the perspective of each client.
 
This discuss is a question I have about PFL overall methodologies.
This is a question I ask because I'm curious about your excellent point of view, apart from the github code. 
Thank you always.

**Comment by IdanAchituve** [comment]
Hi,
I would be happy to share my thoughts, but since this question is not related to this repo's topic, please send me a private email. Also, please elaborate on what type of normalization you are referring to.

Cheers,
Idan
