### ISSUE TITLE
About baseline algorithm pFedHN

### ISSUE THREAD

**Issue by eepLearning** [IdanAchituve/pFedGP#4]
Dear author, firstly, thanks for sharing your awesome work.

 If you don't mind me asking, in the case of pFedHN in your performance comparison table, the baseline that you compared to your amazing pFedGP, is this algorithm a version with a personalized classifier (pFedHN-pc)?

**Comment by IdanAchituve** [comment]
Hi,
Thanks for the kind words.
We compared to pFedHN-pc in the paper.

Idan
